BackendBundle\Entity\User:
   properties:
       name:
           - NotBlank: {message: "Le nom ne peut pas être vide"}
       surname:
           - NotBlank: {message: "Les noms de famille ne peuvent pas être vides"}
       nick:
           - NotBlank: {message: "Le pseudo ne peut pas être vide"}
       email:
           - NotBlank: {message: "L'email ne peut pas être vide"}
           - Email:
                 message: L'e-mail {{value}} n'est pas valide
                 checkMX: false